package com.rideshare.driver_notification_service.drivernotification;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@AllArgsConstructor
@NoArgsConstructor
public class DriverNotificationMessage {
    public String pickUpLongitude;
    public String pickUpLatitude;
    public String driverId;

    // The constructor is removed because it is already generated by the @AllArgsConstructor annotation.
    public String getPickUpLongitude() {
        return pickUpLongitude;
    }
    public void setPickUpLongitude(String pickUpLongitude) {
        this.pickUpLongitude = pickUpLongitude;
    }
    public String getPickUpLatitude() {
        return pickUpLatitude;
    }
    public void setPickUpLatitude(String pickUpLatitude) {
        this.pickUpLatitude = pickUpLatitude;
    }
}
